routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect(route('home'));
//    return view('empty');
});


Route::get('storage/{filename}', function ($filename)
{
    return Image::make(storage_path('public/' . $filename))->response();
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/products', 'HomeController@productsHome')->name('product');
Route::get('/faqs', 'FaqsFrontController@indexHome')->name('faqs');
Route::get('/products', 'HomeController@productsHome')->name('product');
Route::get('/how-to-order', 'HomeController@orderHome')->name('how-to-order');
Route::get('/get-in-touch', 'HomeController@contactHome')->name('get-in-touch');
Route::get('/our-team', 'TeamsFrontController@indexHome')->name('our-team');
Route::get('/design-lab', 'ConfiguratorController@index')->name('configurator');
Route::get('/viewcart', 'step1Controller@cart')->name('cart');
Route::patch('/cart_update/{rowId}', 'step1Controller@cart_update')->name('cart_update');
Route::patch('/cart_decrease/{rowId}', 'step1Controller@cart_decrease')->name('cart_decrease');
Route::patch('/remove/{rowId}', 'step1Controller@remove')->name('remove');
Route::post('/checkout', 'step1Controller@paypal')->name('checkout');
Route::get('/paypal', 'step1Controller@sucess')->name('sucess');

Route::get('/step1-addColor', 'step1Controller@index')->name('step1-addColor');
Route::post('/step1-addColor/uploade', 'step1Controller@uploade')->name('step1-addColor.uploade');
Route::post('/step1-addColor/download-pdf','step1Controller@downloadPDF')->name('step1-addColor.download-pdf');

Route::get('/basic_email', 'step1Controller@basic_email')->name('basic_email');

Route::post('add-to-cart','CartController@addToCart')->name('addToCart');

Route::post('send.mail','CartController@SendMail')->name('send.mail');
Route::post('downloadPDF','CartController@DownloadPDF')->name('download.PDF');

Route::get('/invoice', function () {
    return view('invoice');
//    $pdf = PDF::loadView('invoice');
//    return $pdf->download('Customer-Data.pdf');
});

/*Route::group(['prefix'=>'configurator'],function (){
    Route::resource('step1addColor', 'step1Controller');
});*/

Route::get('/admin', function () {
    return redirect(route('users.index'));
});
Route::group(['prefix'=>'admin'],function (){
    Route::resource('colors', 'ColorController');
    Route::resource('clothes', 'ClothesController');
    Route::post('/clothes/uploade', 'ClothesController@uploade')->name('clothes.uploade');
    Route::resource('users', 'UsersController');
    Route::resource('prints', 'PrintsController');
    Route::resource('product_cat','CategoryController');
    Route::resource('designs','DesignController');
    Route::resource('designs_layers','DesignLayersController');
	Route::post('/designs/addLayers', 'DesignController@addLayers')->name('designs.addLayers');
    Route::resource('clip_arts','ClipArtController');
    Route::resource('fonts','FontController');
    Route::resource('embs','EmbellishmentController');
    Route::resource('sizes','SizeController');
    Route::post('/uploade','PrintsController@uploade')->name('uploade');
    Route::resource('homepage_banners', 'HomepageBannersController');
	Route::resource('text', 'TextController');
	Route::resource('teams', 'TeamsController');
	Route::resource('faqs', 'FaqsController');
	Route::resource('editable_logos', 'EditableLogosController');
	Route::post('/editable_logos/uploade', 'EditableLogosController@uploade')->name('editable_logos.uploade');
	Route::resource('symbols', 'SymbolsController');
	Route::post('/symbols/uploade', 'SymbolsController@uploade')->name('symbols.uploade');
	Route::resource('alphabets', 'AlphabetsController');
	Route::post('/alphabets/uploade', 'AlphabetsController@uploade')->name('alphabets.uploade');
	Route::resource('collars', 'CollarsController');
	Route::post('/collars/uploade', 'CollarsController@uploade')->name('collars.uploade');
	Route::resource('coming_soon', 'ComingSoonController');
});

app/Embellishment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Embellishment extends Model
{
    protected $fillable=[

        'name',
        'file',
        'thumb'

    ];
}

app/Http/Controllers/EmbellishmentController.php
<?php

namespace App\Http\Controllers;

use App\Embellishment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Laracasts\Flash\Flash;

class EmbellishmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $embs = Embellishment::all();
        return view('embellishments.index',compact('embs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('embellishments.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string',
        ]);
        $imageName1 = '';
        $imageName2 = '';
        /*dd($request->hasFile('thumb')." - ".$request->hasFile('file'));
        if ($request->hasFile() == true) {
            // Print the real file names and their sizes
            foreach ($request->getUploadedFiles() as $file) {
                echo $file->getName(), " ", $file->getSize(), "\n";
            }
        }else{
            echo "No upload file"; //<========== CAME HERE!!
        }
        exit;
        */
        if( $request->hasFile('thumb') ) {
            $image = $request->file('thumb');
            $valid_extensions = ['png','jpg'];

            if ( ! in_array( strtolower( $image->getClientOriginalExtension()), $valid_extensions) ) {
                return redirect()->back()->withInput($request->input())->with('error', 'Only .svg, .jpg and .png is allowed extension') ;
            }
            /*****New Code*****/
            $location = public_path() . '/tmp/';

            if (!file_exists($location)) {
                mkdir($location, 0777, true);
            }

            $files = glob($location . '*');
            foreach ($files as $file) {
                if (is_file($file))
                    unlink($file);
            }
            $name = time() . '.png';
            $request->thumb->move($location, $name);
            session(['filename' => $location . $name]);
            // rename($location . $name, public_path().'/images/'. $name);
            $file = basename($location . $name);
            //$filenameWithExt = $image->getClientOriginalName();
            $location = public_path() . '/tmp/' . $file;
            rename($location, public_path() . '/img/embellishments/thumbs/' . $file);
            $imageName2 = $file;
            /*****Old Code*****/
            /*
            $filenameWithExt = $image->getClientOriginalName();
            $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            $extension = $image->getClientOriginalExtension();
            $filenameToStore = $filename . '_' . time() . '.' . $extension;

            $path = $image->storeAs('public/embellishments/thumbs', $filenameToStore);
            $imageName2 = $filenameToStore;
            */
        }

        //echo "File: ".$request->hasFile('file');

        if( $request->hasFile('file') ) {
            echo "file";
            $image = $request->file('file');
            $valid_extensions = ['svg'];

            if ( ! in_array( strtolower( $image->getClientOriginalExtension()), $valid_extensions) ) {
                return redirect()->back()->withInput($request->input())->with('error', 'Only .svg is allowed extension') ;
            }
            /*****New Code*****/
            $location = public_path() . '/tmp/';

            if (!file_exists($location)) {
                mkdir($location, 0777, true);
            }

            $files = glob($location . '*');
            foreach ($files as $file) {
                if (is_file($file))
                    unlink($file);
            }
            $name = time() . '.svg';
            $request->file->move($location, $name);
            session(['filename' => $location . $name]);
            // rename($location . $name, public_path().'/images/'. $name);
            $file = basename($location . $name);

            //$filenameWithExt = $image->getClientOriginalName();
            $location = public_path() . '/tmp/' . $file;
            rename($location, public_path() . '/img/embellishments/' . $file);
            $imageName1 = $file;
            /*****Old Code*****/
            /*
            $filenameWithExt = $image->getClientOriginalName();
            $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            $extension = $image->getClientOriginalExtension();
            $filenameToStore = $filename . '_' . time() . '.' . $extension;

            $path = $image->storeAs('public/embellishments', $filenameToStore);
            $imageName1 = $filenameToStore;
            */
        }

        $embs = [
            'name' => $request->name,
            'file' => $imageName1,
            'thumb' => $imageName2,
        ];
        /*echo "<pre>";
        print_r($embs);
        echo "<pre>";
        exit;*/
        $emb = Embellishment::create($embs);

        Flash::success($emb->name.' added successfully');
        return redirect()->route('embs.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('embellishments.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $emb = Embellishment::find($id);

        return view('embellishments.edit',compact('emb'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $emb = Embellishment::findOrFail($id);
        if( $request->hasFile('file') ) {


            $image = $request->file('file');

            $valid_extensions = ['svg','png'];

            if ( ! in_array( strtolower( $image->getClientOriginalExtension()), $valid_extensions) ) {
                return redirect()->back()->withInput($request->input())->with('error', 'Only .svg, and .png is allowed extension') ;
            }
            Storage::delete('public/embellishments/'. $emb->file);

            $filenameWithExt = $image->getClientOriginalName();
            $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            $extension = $image->getClientOriginalExtension();
            $filenameToStore = $filename . '_' . time() . '.' . $extension;

            $path = $image->storeAs('public/embellishments', $filenameToStore);
            $imageName1 = $filenameToStore;

            $emb->name = $request->name;
            $emb->file= $imageName1;
            $emb->save();

        }elseif( $request->hasFile('thumb') ) {


            $image = $request->file('thumb');

            $valid_extensions = ['svg','png'];

            if ( ! in_array( strtolower( $image->getClientOriginalExtension()), $valid_extensions) ) {
                return redirect()->back()->withInput($request->input())->with('error', 'Only .svg, and .png is allowed extension') ;
            }

            Storage::delete('public/embellishments/thumbs/'. $emb->file);

            $filenameWithExt = $image->getClientOriginalName();
            $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            $extension = $image->getClientOriginalExtension();
            $filenameToStore = $filename . '_' . time() . '.' . $extension;

            $path = $image->storeAs('public/embellishments', $filenameToStore);
            $imageName2 = $filenameToStore;

            $emb->name = $request->name;
            $emb->thumb= $imageName2;
            $emb->save();
        }else{
            $emb->update($request->all());
        }

        Flash::success($emb->name.' updated successfully');
        return redirect()->route('embs.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $emb = Embellishment::findOrFail($id);
//        dd($cat);
        Storage::delete('public/embellishments/' . $emb->file);
        Storage::delete('public/embellishments/thumbs/' . $emb->thumb);
        $emb->delete();
        Flash::success('Deleted Successfully');
        return redirect(route('embs.index'));
    }
}

resources/views/embellishments/create.blade.php
@extends('layouts.admin')

@section('content')
    <section class="content-header">
        <h1>
            Embellishments Create
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'embs.store', 'file' => true, 'enctype'=>'multipart/form-data']) !!}

                    <!-- Name Field -->
                        <div class="form-group col-sm-6">
                            {!! Form::label('name', 'Name:') !!}
                            {!! Form::text('name', null, ['class' => 'form-control']) !!}
                        </div>

                        <!-- Thumb Image Field -->
                        <div class="form-group col-sm-6">
                            {!! Form::label('thumb', 'Thumb') !!}
                            {!! Form::file('thumb', null, ['class' => 'form-control']) !!}
                        </div>

                        <!-- Embs Image Field -->
                        <div class="form-group col-sm-6">
                            {!! Form::label('file', 'File') !!}
                            {!! Form::file('file', null, ['class' => 'form-control']) !!}
                        </div>

                        <!-- Submit Field -->
                        <div class="form-group col-sm-12">
                            {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                            <a href="{!! route('embs.index') !!}" class="btn btn-default">Cancel</a>
                        </div>

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/embellishments/edit.blade.php
@extends('layouts.admin')

@section('content')
    <section class="content-header">
        <h1>
            Embellishments
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                {!! Form::model($emb, ['route' => ['embs.update', $emb->id],'enctype'=>'multipart/form-data','method' => 'patch']) !!}


                <!-- Name Field -->
                    <div class="form-group col-sm-6">
                        {!! Form::label('name', 'Name:') !!}
                        {!! Form::text('name',old('name'), ['class' => 'form-control']) !!}
                    </div>

                    <!-- Image Field -->
                    <div class="form-group col-sm-6">
                        {!! Form::label('file', 'File') !!}
                        {!! Form::file('file', null, ['class' => 'form-control image']) !!}

                    </div>

                    <div class="form-group col-sm-6">
                        {!! Form::label('thumb', 'Thumb') !!}
                        {!! Form::file('thumb', null, ['class' => 'form-control image']) !!}

                    </div>

                    <!-- Submit Field -->
                    <div class="form-group col-sm-12">
                        {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                        <a href="{!! route('embs.index') !!}" class="btn btn-default">Cancel</a>
                    </div>

                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/embellishments/index.blade.php
@extends('layouts.admin')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Embellishments</h1>
        <h1 class="pull-right">
            <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('embs.create') !!}">Add new</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                <table class="table table-responsive" id="dataTable">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>File</th>
                        <th>Thumb</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($embs as $emb)
                        <tr>
                            <td>{{$emb->name}}</td>
                            <td>
                                <img src="{{asset('img/embellishments/')}}/{!! $emb->file !!}" alt="img">
                            </td>
                            <td>
                                <img width="40%" class="cloth" src="{{asset('img/embellishments/thumbs/')}}/{!! $emb->thumb !!}" alt="img">
                            </td>
                            <td>
                                {!! Form::open(['route' => ['embs.destroy', $emb->id], 'method' => 'delete']) !!}
                                <div class='btn-group'>
                                    <a href="{!! route('embs.show', [$emb->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                                    <a href="{!! route('embs.edit', [$emb->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                                </div>
                                {!! Form::close() !!}
                            </td>
                        </tr>
                    @empty
                        <td>No embellishments added yet.</td>

                    @endforelse
                    </tbody>
                </table>
            </div>
        </div>
        <div class="text-center">

        </div>
    </div>
@endsection